CREATE DATABASE [DBFG]
ON PRIMARY
(
	NAME = N'DBFG',
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\DBFG.mdf',
	SIZE = 4096KB,	FILEGROWTH = 1024KB
),
(
	NAME = N'DBFG_01',
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\DBFG_01.ndf',
	SIZE = 4096KB,	FILEGROWTH = 1024KB
)
LOG ON
(
	NAME = N'DBFG_log',
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\DBFG_log.ldf',
	SIZE = 1024KB,	FILEGROWTH = 10%
)
GO

SELECT * FROM SYS.filegroups;
GO

ALTER DATABASE [DBFG] ADD FILEGROUP [SECFG];
GO

ALTER DATABASE [DBFG]
ADD FILE
(
	NAME = N'Test_01',
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\Test_01.ndf',
	SIZE = 1024KB, FILEGROWTH = 10%
),
(
	NAME = N'Test_02',
	FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\Test_02.ndf',
	SIZE = 1024KB, FILEGROWTH = 10%
)
TO FILEGROUP [SECFG];
GO
