CREATE DATABASE PMDB;
GO

USE PMDB;
GO

CREATE SCHEMA PM;
GO

CREATE TABLE PM.Managers
(
	Id INT PRIMARY KEY,
	Email VARCHAR(100) NOT NULL
);
GO

CREATE TABLE PM.Companies
(
	CRNNO INT NOT NULL,
	CompanyName VARCHAR(100) NOT NULL,

	PRIMARY KEY (CRNNO)
);
GO

CREATE TABLE PM.Technologies
(
	Id INT NOT NULL,
	Name VARCHAR(100) NOT NULL,

	PRIMARY KEY(Id)
);
GO

CREATE TABLE PM.Projects
(
	PRJNO INT PRIMARY KEY,
	Title VARCHAR(100) NOT NULL,
	ManagerId INT FOREIGN KEY REFERENCES PM.Managers(Id) NOT NULL,
	StartDate DATETIME2(7) NOT NULL, 
	InitialCost DECIMAL(18, 2) NOT NULL,
	Parked BIT NOT NULL,
	CRNNO INT FOREIGN KEY REFERENCES PM.Companies(CRNNO) NOT NULL
);
GO

CREATE TABLE PM.ProjectTechnologies
(
	PRJNO INT NOT NULL,
	TCHID INT NOT NULL,
	
	FOREIGN KEY (PRJNO) REFERENCES PM.Projects(PRJNO),
	FOREIGN KEY (TCHID) REFERENCES PM.Technologies(Id),
	PRIMARY KEY(PRJNO, TCHID)
);
GO